services:
  embyboss:
    image: qinayui/sakura_embyboss:latest
    container_name: embyboss
    restart: always
    networks:
      yui:
        ipv4_address: 172.30.0.21
    volumes:
      - ./config.json:/app/config.json
      - ./log:/app/log
    ports:
      - '22100:8838'

  embyboss2:
    image: qinayui/sakura_embyboss:latest
    container_name: embyboss2
    restart: always
    networks:
      yui:
        ipv4_address: 172.30.0.22
    volumes:
      - ./config2.json:/app/config.json
      - ./log2:/app/log
    ports:
      - '22200:8838'

networks:
  yui:
    external: true
