services:
  embyboss:
    image: qinayui/sakura_embyboss:latest # ARM与AMD镜像名称相同，会自动加载适合的镜像
    container_name: embyboss
    restart: always
    network_mode: host
    volumes:
      - ./config.json:/app/config.json
      - ./log:/app/log
#    ports:
#      - '8838:8838' # 为api服务映射端口 host模式无需操作